//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopManagementClient.BillServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bill", Namespace="http://schemas.datacontract.org/2004/07/Small_Shop_Management_System")]
    [System.SerializableAttribute()]
    public partial class Bill : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long MobileNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TotalAmountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long MobileNo {
            get {
                return this.MobileNoField;
            }
            set {
                if ((this.MobileNoField.Equals(value) != true)) {
                    this.MobileNoField = value;
                    this.RaisePropertyChanged("MobileNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalAmount {
            get {
                return this.TotalAmountField;
            }
            set {
                if ((this.TotalAmountField.Equals(value) != true)) {
                    this.TotalAmountField = value;
                    this.RaisePropertyChanged("TotalAmount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BillServiceReference.IBillService")]
    public interface IBillService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/GetBills", ReplyAction="http://tempuri.org/IBillService/GetBillsResponse")]
        System.Data.DataSet GetBills();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/GetBills", ReplyAction="http://tempuri.org/IBillService/GetBillsResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetBillsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/GenerateBill", ReplyAction="http://tempuri.org/IBillService/GenerateBillResponse")]
        string GenerateBill(ShopManagementClient.BillServiceReference.Bill bill);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBillService/GenerateBill", ReplyAction="http://tempuri.org/IBillService/GenerateBillResponse")]
        System.Threading.Tasks.Task<string> GenerateBillAsync(ShopManagementClient.BillServiceReference.Bill bill);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBillServiceChannel : ShopManagementClient.BillServiceReference.IBillService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BillServiceClient : System.ServiceModel.ClientBase<ShopManagementClient.BillServiceReference.IBillService>, ShopManagementClient.BillServiceReference.IBillService {
        
        public BillServiceClient() {
        }
        
        public BillServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BillServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BillServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BillServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetBills() {
            return base.Channel.GetBills();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetBillsAsync() {
            return base.Channel.GetBillsAsync();
        }
        
        public string GenerateBill(ShopManagementClient.BillServiceReference.Bill bill) {
            return base.Channel.GenerateBill(bill);
        }
        
        public System.Threading.Tasks.Task<string> GenerateBillAsync(ShopManagementClient.BillServiceReference.Bill bill) {
            return base.Channel.GenerateBillAsync(bill);
        }
    }
}
